-- Date Validation Function
CREATE OR REPLACE FUNCTION GET_VALIDATED_DATE(v_DATE IN VARCHAR2)
RETURN DATE IS
  v_OUTPUT VARCHAR2(50);
  v_OUTPUT_date DATE;
BEGIN
  IF v_DATE IS NULL THEN RETURN NULL; END IF;

  v_OUTPUT := v_DATE;
  v_OUTPUT := REPLACE(v_OUTPUT, '-01-', '-JAN-');
  v_OUTPUT := REPLACE(v_OUTPUT, '-02-', '-FEB-');
  v_OUTPUT := REPLACE(v_OUTPUT, '-03-', '-MAR-');
  v_OUTPUT := REPLACE(v_OUTPUT, '-04-', '-APR-');
  v_OUTPUT := REPLACE(v_OUTPUT, '-05-', '-MAY-');
  v_OUTPUT := REPLACE(v_OUTPUT, '-06-', '-JUN-');
  v_OUTPUT := REPLACE(v_OUTPUT, '-07-', '-JUL-');
  v_OUTPUT := REPLACE(v_OUTPUT, '-08-', '-AUG-');
  v_OUTPUT := REPLACE(v_OUTPUT, '-09-', '-SEP-');
  v_OUTPUT := REPLACE(v_OUTPUT, '-10-', '-OCT-');
  v_OUTPUT := REPLACE(v_OUTPUT, '-11-', '-NOV-');
  v_OUTPUT := REPLACE(v_OUTPUT, '-12-', '-DEC-');

  v_OUTPUT_date := TO_DATE(v_OUTPUT,'DD-MON-YYYY');
  RETURN v_OUTPUT_date;
EXCEPTION
  WHEN OTHERS THEN RETURN NULL; -- Handle invalid date cases
END;
/

-- Phone Number Validation Function
CREATE OR REPLACE FUNCTION GET_VALIDATED_PHONENUMBER(v_PHONE_NUMBER in VARCHAR2)
RETURN VARCHAR2 IS
  v_OUTPUT VARCHAR2(50);
BEGIN
  v_OUTPUT := NVL(v_PHONE_NUMBER, '');
  v_OUTPUT := REGEXP_REPLACE(v_OUTPUT, '[^0-9]', ''); -- Remove non-numeric
  RETURN v_OUTPUT;
END;
/

-- Number Validation Function
CREATE OR REPLACE FUNCTION GET_VALIDATED_NUMBER(v_NUMBER_VALUE IN VARCHAR2) 
RETURN NUMBER IS
  v_OUTPUT VARCHAR2(50);
  v_OUTPUT_number NUMBER(10);
BEGIN
  v_OUTPUT := NVL(v_NUMBER_VALUE, '0');
  v_OUTPUT := REGEXP_REPLACE(v_OUTPUT, '[^0-9]', ''); -- Remove non-numeric
  v_OUTPUT_number := TO_NUMBER(v_OUTPUT);
  RETURN v_OUTPUT_number;
EXCEPTION
  WHEN VALUE_ERROR THEN RETURN 0; -- Handle conversion error
END;
/
